### PR TITLE
Added new project - Backdoor

### PR DESCRIPTION
**Pull request by VKspyder2003**
Signed-off-by: Spyder <kapoorvishwas0123@gmail.com>

### CODE REVIEW

**Comment by itsmedeepak** [comment]
Can you please add any preview images of its readme

**Review by itsmedeepak — CHANGES_REQUESTED** [review]
add readme

**Comment by VKspyder2003** [comment]
[README.txt](https://github.com/itsmedeepak/Hacktoberfest-2022/files/9746083/README.txt)

**Comment by VKspyder2003** [comment]
Done

**Review by itsmedeepak — APPROVED** [review]

**Pull request merged**
