### PR TITLE
use binary search to search for data in mysql database

### PR DESCRIPTION
**Pull request by GUPTA-DIKSHITA**
Code contains how to create a database using mysql commands. MYSQL workbench is used for the same. Then search in the database using the convenient and efficient binary search. code is written in python

### CODE REVIEW

**Review by itsmedeepak — CHANGES_REQUESTED** [review]
Upload folder

**Comment by GUPTA-DIKSHITA** [comment]
Sir I have looked into the changes you told to made.Should I upload Folder containing code for both the tasks: to create the database and to use the database for searching?Sent from Android deviceOn 17-Oct-2022 00:03, Deepak Kumar ***@***.***> wrote:
@itsmedeepak requested changes on this pull request.

Upload folder

**Comment by itsmedeepak** [comment]
Hey there's confirm bw branches try to create new PR
Next time please upload folder of project it will help to maintain the structure of project

**Comment by GUPTA-DIKSHITA** [comment]
I have uploaded the project in a folder now(MYSQL), via creating a new branch.Please look into thatSent from Android deviceOn 17-Oct-2022 15:46, Deepak Kumar ***@***.***> wrote:
Hey there's confirm bw branches try to create new PR
Next time please upload folder of project it will help to maintain the structure of project

**Pull request closed without merging**
